### ISSUE TITLE
1.11.0 roadmap

### ISSUE THREAD

**Issue by alkihis** [PLhery/node-twitter-api-v2#189]
- [x] Core plugin implementation
- [x] Refactor of `.uploadMedia` type argument
- [x] Fix OAuth2 scope encoding (and other possible encoding issues)
- [x] Precise compression option [BREAKING: disableCompression>compression]
- [x] Refactor of `ClientRequestMaker` to a external class [BREAKING: .send/.sendStream are not exposed anymore]
- [x] Implement and publish two first plugins: `plugin-cache-core` and `plugin-rate-limit`

**Comment by alkihis** [comment]
Breaking changes won't massively affect developers, as `.send`/`.sendStream` is restricted to very advanced usage, and `disableCompression` is very specific and recent.
